Repository Dan0804/wedding_app, pull requests merged in 2024-06, with the labels that each got.

#29 백엔드 도메인 API 등록
  lib/app/services/auth_service.dart
  lib/app/services/card/create_card_api.dart
  lib/app/services/card/fetch_tile_api.dart
  lib/config.dart
  lib/main.dart
  pubspec.lock
Labels: refactor

#30 Http -> Https로 수정
  lib/config.dart
Labels: bug

#31 insert test id
  lib/app/widgets/login_form.dart
Labels: enhancement

#34 Edit get tile list refreshed
  lib/app/screens/tile_list_screen.dart
  lib/app/services/card/delete_tile_api.dart
  lib/app/services/card/edit_tile_api.dart
  lib/app/services/card/fetch_tile_api.dart
  lib/app/widgets/delete_tile_pop_up.dart
  lib/app/widgets/edit_tile_pop_up.dart
  lib/main.dart
Labels: bug

#35 [#6]: 카드 수정 로직
  lib/app/screens/tile_list_screen.dart
  lib/app/services/card/fetch_tile_api.dart
  lib/app/widgets/tile_list.dart
Labels: bug

#37 Fixed refresh endless
  lib/app/services/card/fetch_tile_api.dart
  lib/app/widgets/delete_tile_pop_up.dart
  lib/app/widgets/edit_tile_pop_up.dart
  lib/app/widgets/tile_widget.dart
Labels: enhancement

#38 Refresh fix
  lib/app/screens/create_card_screen.dart
  lib/app/screens/tile_list_screen.dart
  lib/app/services/card/create_card_api.dart
  lib/app/services/card/delete_tile_api.dart
  lib/app/services/card/edit_tile_api.dart
  lib/app/services/card/fetch_tile_api.dart
  lib/app/widgets/delete_tile_pop_up.dart
  lib/app/widgets/edit_tile_pop_up.dart
  lib/main.dart
Labels: bug

#40 Changing edit card function
  lib/app/services/card/fetch_tile_api.dart
  lib/app/widgets/edit_tile_pop_up.dart
  lib/app/widgets/tile_widget.dart
Labels: enhancement, tile

#43 delete unused tile form and detail file
  lib/tile_set/text_tile_detail.dart
  lib/tile_set/tile_form.dart
Labels: refactor

#44 move fetchTileApi from tile_list_screen to main_screen
  lib/app/screens/main_screen.dart
  lib/app/screens/tile_list_screen.dart
Labels: refactor

#45 Show schedules on calendar
  lib/app/screens/create_card_screen.dart
  lib/app/screens/main_screen.dart
  lib/app/services/card/fetch_tile_api.dart
  lib/app/widgets/edit_tile_pop_up.dart
  lib/calender_set/calender.dart
  lib/calender_set/calender_package.dart
Labels: enhancement

#46 changed desing of count in calendar
  lib/calender_set/calender.dart
  lib/calender_set/calender_package.dart
Labels: refactor

#47 Show tile data in calendar
  lib/app/services/card/fetch_tile_api.dart
  lib/calender_set/calender.dart
  lib/calender_set/calender_detail_tile.dart
Labels: enhancement

#48 delete tile_service file and remove unused code
  lib/app/services/card/fetch_tile_api.dart
  lib/app/widgets/register_form.dart
  lib/app/widgets/tile_widget.dart
  lib/main.dart
  lib/service_set/tile_service.dart
Labels: refactor

#49 Arrange files tree
  lib/app/screens/create_card_screen.dart
  lib/app/screens/login_screen.dart
  lib/app/screens/main_screen.dart
  lib/app/screens/tile_list_screen.dart
  lib/app/screens/user_register_screen.dart
  lib/app/services/auth_service.dart
  lib/app/services/tile_service.dart
  lib/app/widgets/forAuth/login_form.dart
  lib/app/widgets/forAuth/partner_enter_pop_up.dart
  lib/app/widgets/forAuth/register_form.dart
  lib/app/widgets/forCalender/calender.dart
  lib/app/widgets/forCalender/calender_detail_tile.dart
  lib/app/widgets/forCalender/calender_package.dart
  lib/app/widgets/forTile/delete_tile_pop_up.dart
  lib/app/widgets/forTile/edit_tile_pop_up.dart
  lib/app/widgets/forTile/tile_list.dart
  lib/app/widgets/forTile/tile_widget.dart
  lib/main.dart
  lib/util/config.dart
Labels: refactor

#50 change title and logout button
  lib/app/screens/main_screen.dart
Labels: enhancement

#51 add function showing tile in calendar detail when first build
  lib/app/services/tile_service.dart
  lib/app/widgets/forCalender/calender.dart
Labels: enhancement

#52 Change single child scroll view range
  lib/app/widgets/forCalender/calender.dart
  lib/app/widgets/forCalender/calender_package.dart
Labels: enhancement

#53 Change place of delete button
  lib/app/widgets/forTile/delete_tile_pop_up.dart
  lib/app/widgets/forTile/edit_tile_pop_up.dart
Labels: enhancement

#54 change variable in firstGetTilesForDay
  lib/app/widgets/forCalender/calender.dart
Labels: bug
